#!/bin/bash

#-----------------------------COPY RIGHT-------------------------------#
# Author: Khai Tran
# Date: June 4, 2024
# Description: A simple address database based on bash script

#-----------------------------REFERENCE-------------------------------#
# Chat GPT
# Website: Emertxe - Linux Systems Project - Address Database

#-----------------------------GLOBAL VARIABLE-------------------------------#
#ANSI color codes
txtred='\e[1;31m'
txtgreen='\e[1;32m'
txtyellow='\e[1;33m'
txtblue='\e[1;34m'
txtreset='\e[0m'

# The globals
name=" "
email=" "
tel_no=" "
mob_no=" "
place=" "
message=" "
id=" "
id_temp=" "

# Log variable
name_log=" "
email_log=" "
tel_no_log=" "
mob_no_log=" "
place_log=" "
message_log=" "
mode=""
time=""

# Flag
flag_add_entry_error=false
flag_choose_id_in_search=false
flag_edit_entry_error=false
flag_show_search=true

# Country code
COUNTRY_CODE="+84"

# Search and edit variables
save_or_all="7. All"
Search="${txtred}Search${txtreset}"
Edit="Edit"

# Time out periods
TIME_OUT=10

# Menu state
MENU_STATE="menu_header"
FIELD_MENU_STATE="field"
SEARCH_EDIT_STATE="search"
SEARCH_MENU_STATE="field"
EDIT_MENU_STATE="field"

#-----------------------------CREATE FILE-------------------------------#
# Set the path to the database 
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" 
LOG_DIR="$SCRIPT_DIR/log"
DATABASE="$SCRIPT_DIR/mydatabase.db"
ADDRESS_DATABASE_CSV="$LOG_DIR/address_database.csv"
LOG_FILE_CSV="$LOG_DIR/log_file.csv"

# Ensure the database file exists
if [ ! -f "$DATABASE" ]; then
	sqlite3 "$DATABASE" "CREATE TABLE IF NOT EXISTS address(
							id INTEGER PRIMARY KEY AUTOINCREMENT,
							name TEXT,
							email TEXT,
							tel_no TEXT,
							mob_no TEXT,
							place TEXT,
							message TEXT
	);"

	sqlite3 "$DATABASE" "CREATE TABLE IF NOT EXISTS log(
							id INTEGER PRIMARY KEY AUTOINCREMENT,
                            id_address_book TEXT,
							name TEXT,
							email TEXT,
							tel_no TEXT,
							mob_no TEXT,
							place TEXT,
							message TEXT,
                            mode TEXT,
                            time TEXT
	);"
fi

# Ensure the log directory exists
if [ ! -d "$LOG_DIR" ]; then
    mkdir -p "$LOG_DIR"
fi

# Ensure the log file exists
if [ ! -f "$ADDRESS_DATABASE_CSV" ]; then
    touch "$ADDRESS_DATABASE_CSV"
    chmod 755 "$ADDRESS_DATABASE_CSV"
fi

if [ ! -f "$LOG_FILE_CSV" ]; then
    touch "$LOG_FILE_CSV"
    chmod 755 "$LOG_FILE_CSV"
fi

#-----------------------------MAIN MENU-------------------------------#
function menu_header()
{
	# TODO Just to print welcome menu presntation
	clear
	echo -e "$(
	    cat <<- _EOF_
My Database Project
Please choose the below options:

1. Add Entry
2. Search / Edit Entry
3. Show log file
${txtred}x${txtreset}. Exit

Note: Script Timeout is set
	_EOF_
    )"
	
	read -r -t $TIME_OUT -p "Please choose your option: "

	if [[ "$REPLY" == "" ]]; then
		echo -e "\t"
		exit 0
	fi

	if [[ "$REPLY" == "x" ]]; then
		exit 0
	fi
}

function choose_header_option()
{
	# TODO Just to choose the menu header option
	local option=$REPLY
	case $option in
		1)
			MENU_STATE="field_menu"
		;;

		2)
			MENU_STATE="search_edit_entry"
		;;

        3)
            MENU_STATE="log_file"
        ;;

		x)
			MENU_STATE="menu_header"
		;;
	esac
}


#-----------------------------ADD (FIELD) MENU-------------------------------#
function field_menu()
{
	# TODO to print a selected user information 
	# Name, Email, Tel no, Mob num, Address, Message
	clear
	echo -e "$(
		cat <<- _EOF_
			My Database Project
			Please choose the below options:

			Add New Entry Screen:

			1. Name			: $name
			2. Email		: $email
			3. Tel No		: $tel_no
			4. Mob No		: $mob_no
			5. Place		: $place
			6. Message		: $message
			${txtred}x${txtreset}. Exit

		_EOF_
	)"

	if [[ $FIELD_MENU_STATE == "field" ]]; then
		read -r -p "Please choose the field to be added: "
	else 
		read -r -p "Please enter the $FIELD_MENU_STATE: "
	fi

	true;
}

function choose_field_menu_option()
{
	if [[ $FIELD_MENU_STATE == "field" ]]; then
		local option="$REPLY"
		case $option in
			1)
				FIELD_MENU_STATE="Name"
			;;

			2)
				FIELD_MENU_STATE="Email"
			;;

			3)
				FIELD_MENU_STATE="Telephone Number"
			;;

			4)
				FIELD_MENU_STATE="Mobile Number"
			;;

			5)
				FIELD_MENU_STATE="Place"
			;;

			6)
				FIELD_MENU_STATE="Message"
			;;

			x)
				FIELD_MENU_STATE="field"
				database_entry
				reset_global_value
				MENU_STATE="menu_header"
			;;
		esac
	fi
}

function add_entry()
{
	# TODO adding a new entry to database
	# 1. Validates the entries
	# 2. Add to database

	if [[ $FIELD_MENU_STATE != "field" ]]; then
		local option="$REPLY"
		case $FIELD_MENU_STATE in
			"Name")
				validate_entry "$option" "$FIELD_MENU_STATE"
				if [[ $flag_add_entry_error == "false" ]]; then
					FIELD_MENU_STATE="field"
				fi
				REPLY="" # Reset Reply
				true
			;;

			"Email")
				validate_entry "$option" "$FIELD_MENU_STATE"
				if [[ $flag_add_entry_error == "false" ]]; then
					FIELD_MENU_STATE="field"
				fi
				REPLY="" # Reset Reply
				true
			;;

			"Telephone Number")
				validate_entry "$option" "$FIELD_MENU_STATE"
				if [[ $flag_add_entry_error == "false" ]]; then
					FIELD_MENU_STATE="field"
				fi
				REPLY="" # Reset Reply
				true
			;;

			"Mobile Number")
				validate_entry "$option" "$FIELD_MENU_STATE"
				if [[ $flag_add_entry_error == "false" ]]; then
					FIELD_MENU_STATE="field"
				fi
				REPLY="" # Reset Reply
				true
			;;

			"Place")
				validate_entry "$option" "$FIELD_MENU_STATE"
				if [[ $flag_add_entry_error == "false" ]]; then
					FIELD_MENU_STATE="field"
				fi
				REPLY="" # Reset Reply
				true
			;;

			"Message")
				message="$option"
				FIELD_MENU_STATE="field"
				REPLY="" # Reset Reply
				true
			;;
		esac
	fi
}

function validate_entry()
{
	# TODO Inputs entered by user must be verified and validated as per fields
	# 1. Names should have only alphabets
	# 2. Emails must have a @ symbols and ending with .<domain> Eg: user@mail.com
	# 3. Mobile/Tel numbers must have 10 digits .
	# 4. Place must have only alphabets
	local option="$1"
	local state="$2"
	# echo "Validate entry with $option and $state"
	# sleep 4
	case $state in
		"Name")
			if [[ ! "$option" =~ ^[a-zA-Z]+$ ]]; then
				echo -e "${txtred}Invalid name. Only alphabets are allowed.${txtreset}"
				flag_add_entry_error=true
                flag_edit_entry_error=true
				sleep 2
			else
				name=$option
				flag_add_entry_error=false
                flag_edit_entry_error=false
			fi
		;;

		"Email")
			if [[ ! "$option" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
				echo -e "${txtred}Invalid email. Must be in the format user@mail.com.${txtreset}"
				flag_add_entry_error=true
                flag_edit_entry_error=true
				sleep 2
			else
				email=$option
				flag_add_entry_error=false
                flag_edit_entry_error=false
			fi
		;;

		"Telephone Number")
			if [[ ! "$option" =~ ^[0-9]{10}$ ]]; then
				echo -e "${txtred}Invalid mobile number. Must be exactly 10 digits.${txtreset}"
				flag_add_entry_error=true
                flag_edit_entry_error=true
				sleep 2
			else
				tel_no="$COUNTRY_CODE-$option"
				flag_add_entry_error=false
                flag_edit_entry_error=false
			fi
		;;


		"Mobile Number")
			if [[ ! "$option" =~ ^[0-9]{10}$ ]]; then
				echo -e "${txtred}Invalid mobile number. Must be exactly 10 digits.${txtreset}"
				flag_add_entry_error=true
                flag_edit_entry_error=true
				sleep 2
			else
				mob_no="$COUNTRY_CODE-$option"
				flag_add_entry_error=false
                flag_edit_entry_error=false
			fi
		;;

		"Place")
			if [[ ! "$option" =~ ^[a-zA-Z]+$ ]]; then
				echo -e "${txtred}Invalid place. Only alphabets are allowed.${txtreset}"
				flag_add_entry_error=true
                flag_edit_entry_error=true
				sleep 2
			else
				place=$option
				flag_add_entry_error=false
                flag_edit_entry_error=false
			fi
		;;
	esac
	# echo "flag_add_entry_error is $flag_add_entry_error"
	# sleep 3
	true;
}

function database_entry()
{
	# TODO user inputs will be written to database file
	# TODO symbol ' ' is important
	# 1. If some fields are missing add consicutive ','. Eg: user,,,,,
    local current_time
    current_time=$(date '+%Y-%m-%d %H:%M:%S')
	sqlite3 "$DATABASE" "INSERT INTO address (name, email, tel_no, mob_no, place, message) VALUES ('$name', '$email', '$tel_no', '$mob_no', '$place', '$message');"		
    id_temp=$(sqlite3 "$DATABASE" "SELECT id FROM address ORDER BY id DESC LIMIT 1;")
    log "INSERT" "$current_time"
}

function reset_global_value()
{
	name=" "
	email=" "
	tel_no=" "
	mob_no=" "
	place=" "
	message=" "
	id=" "
    mode=" "
    time=" "
}


#-----------------------------SEARCH MENU-------------------------------#
function search_and_edit()
{
	# TODO UI for editing and searching 
	clear
	echo -e "$(
		cat <<- _EOF_
			My Database Project
			Please choose the below options:

			$Search / $Edit by:

			1. Name			: $name
			2. Email		: $email
			3. Tel No		: $tel_no
			4. Mob No		: $mob_no
			5. Place		: $place
			6. Message		: $message
			$save_or_all 
			${txtred}x${txtreset}. Exit

		_EOF_
	)"

	if [[ $SEARCH_EDIT_STATE == "search" ]]; then
		if [[ $SEARCH_MENU_STATE == "field" ]]; then
			read -r -p "Please choose the field to be searched: "
		else
			if [[ $SEARCH_MENU_STATE == "All" ]]; then
				true
			else
				read -r -p "Please enter the $SEARCH_MENU_STATE: " 
			fi
		fi
	fi

	if [[ $SEARCH_EDIT_STATE == "edit" ]]; then
		if [[ $EDIT_MENU_STATE == "field" ]]; then
			read -r -p "Please choose your option: "
		else
			if [[ $EDIT_MENU_STATE == "Save" ]]; then
				true
			else
				read -r -p "Please enter the new $EDIT_MENU_STATE: " 
			fi
		fi
    fi
	true;
}

function change_between_search_edit()
{
	# TODO Show changes between search and edit menu
	if [[ $SEARCH_EDIT_STATE == "edit" ]]; then
		save_or_all="${txtred}7. Save${txtreset}"
		Search="Search"
		Edit="${txtred}Edit${txtreset}"
	else
		save_or_all="7. All"
		Search="${txtred}Search${txtreset}"
		Edit="Edit"
	fi
}

function validate_id()
{
	local id_input="$1"
	local ids=("${@:2}")
	for id_i in "${ids[@]}"; do
		if [ "$id_input" -eq "$id_i" ]; then
			flag_choose_id_in_search=false
			break
		else
			flag_choose_id_in_search=true
		fi
	done
	if [[ $flag_choose_id_in_search == false ]]; then
        read -r -p "Do you want to delete it? (y/n) "
        delete_choose_id "$REPLY"
        REPLY=""
	else
		echo -e "${txtred}Wrong id.${txtreset}"
		sleep 3
	fi
}

function delete_choose_id()
{
    local option="$1"
    case $option in
        "yes" | "y" | "Y" | "Yes" | "YES")
            local current_time
            current_time=$(date '+%Y-%m-%d %H:%M:%S')
            log "DELETE" "$current_time" 
            sqlite3 "$DATABASE" "DELETE FROM address WHERE id='$id'"    
        ;;
        
        *)
            SEARCH_EDIT_STATE="edit"
            SEARCH_MENU_STATE="field"
        ;;
    esac
}

function search_operation()
{
	# TODO Ask user for a value to search
	# 1. Value can be from any field of an entry.
	# 2. One by one iterate through each line of database file and search for the entry
	# 3. If available display all fields for that entry
	# 4. Prompt error incase not available
	# 5. Delete id if users want
	if [[ $SEARCH_EDIT_STATE == "search" ]]; then
		if [[ $SEARCH_MENU_STATE != "field" ]]; then
			local option="$REPLY"
			local result=""
			local id_database=""
            if [[ "$option" == "x" ]]; then
                SEARCH_MENU_STATE="field"
                REPLY=""
            else
                case $SEARCH_MENU_STATE in
                    "Name")
                        result=$(sqlite3 -header -column "$DATABASE" "SELECT * FROM address WHERE name='$option';")
                        id_database=$(sqlite3 "$DATABASE" "SELECT id FROM address WHERE name='$option';")
                        if [ -z "$result" ]; then
                            echo -e "${txtyellow}Invalid. Found no Name${txtreset}"
                            sleep 3
                        else
                            echo "$result"
                            IFS=$'\n' read -r -d '' -a ids <<< "$id_database"
                            while true; do 
                                read -r -p "Select the user id to be displayed: "  
                                id="$REPLY"
                                validate_id "$id" "${ids[@]}"
                                if [[ "$flag_choose_id_in_search" == "false" ]]; then
                                    break;
                                fi
                            done
                        fi
                        true	
                    ;;

                    "Email")
                        result=$(sqlite3 -header -column "$DATABASE" "SELECT * FROM address WHERE email='$option';")
                        id_database=$(sqlite3 "$DATABASE" "SELECT id FROM address WHERE email='$option';")
                        if [ -z "$result" ]; then
                            echo -e "${txtyellow}Invalid. Found no Email${txtreset}"
                            sleep 3
                        else
                            echo "$result"
                            IFS=$'\n' read -r -d '' -a ids <<< "$id_database"
                            while true; do 
                                read -r -p "Select the user id to be displayed: "  
                                id="$REPLY"
                                validate_id "$id" "${ids[@]}"
                                if [[ "$flag_choose_id_in_search" == "false" ]]; then
                                    break;
                                fi
                            done
                        fi
                        true	
                    ;;

                    "Telephone Number")
                        echo "option = $option"
                        sleep 3
                        result=$(sqlite3 -header -column "$DATABASE" "SELECT * FROM address WHERE tel_no='$option';")
                        id_database=$(sqlite3 "$DATABASE" "SELECT id FROM address WHERE tel_no='$option';")
                        if [ -z "$result" ]; then
                            echo -e "${txtyellow}Invalid. Found no Telephone Number${txtreset}"
                            sleep 3
                        else
                            echo "$result"
                            IFS=$'\n' read -r -d '' -a ids <<< "$id_database"
                            while true; do 
                                read -r -p "Select the user id to be displayed: "  
                                id="$REPLY"
                                validate_id "$id" "${ids[@]}"
                                if [[ "$flag_choose_id_in_search" == "false" ]]; then
                                    break;
                                fi
                            done
                        fi
                        true	
                    ;;

                    "Mobile Number")
                        result=$(sqlite3 -header -column "$DATABASE" "SELECT * FROM address WHERE mob_no='$option';")
                        id_database=$(sqlite3 "$DATABASE" "SELECT id FROM address WHERE mob_no='$option';")
                        if [ -z "$result" ]; then
                            echo -e "${txtyellow}Invalid. Found no Mobile Number${txtreset}"
                            sleep 3
                        else
                            echo "$result"
                            IFS=$'\n' read -r -d '' -a ids <<< "$id_database"
                            while true; do 
                                read -r -p "Select the user id to be displayed: "  
                                id="$REPLY"
                                validate_id "$id" "${ids[@]}"
                                if [[ "$flag_choose_id_in_search" == "false" ]]; then
                                    break;
                                fi
                            done
                        fi
                        true	
                    ;;

                    "Place")
                        result=$(sqlite3 -header -column "$DATABASE" "SELECT * FROM address WHERE place='$option';")
                        id_database=$(sqlite3 "$DATABASE" "SELECT id FROM address WHERE place='$option';")
                        if [ -z "$result" ]; then
                            echo -e "${txtyellow}Invalid. Found no Place${txtreset}"
                            sleep 3
                        else
                            echo "$result"
                            IFS=$'\n' read -r -d '' -a ids <<< "$id_database"
                            while true; do 
                                read -r -p "Select the user id to be displayed: "  
                                id="$REPLY"
                                validate_id "$id" "${ids[@]}"
                                if [[ "$flag_choose_id_in_search" == "false" ]]; then
                                    break;
                                fi
                            done
                        fi
                        true	
                    ;;

                    "Message")
                        result=$(sqlite3 -header -column "$DATABASE" "SELECT * FROM address WHERE message='$option';")
                        id_database=$(sqlite3 "$DATABASE" "SELECT id FROM address WHERE message='$option';")
                        if [ -z "$result" ]; then
                            echo -e "${txtyellow}Invalid. Found no Message${txtreset}"
                            sleep 3
                        else
                            echo "$result"
                            IFS=$'\n' read -r -d '' -a ids <<< "$id_database"
                            while true; do 
                                read -r -p "Select the user id to be displayed: "  
                                id="$REPLY"
                                validate_id "$id" "${ids[@]}"
                                if [[ "$flag_choose_id_in_search" == "false" ]]; then
                                    break;
                                fi
                            done
                        fi
                        true	
                    ;;

                    "All")
                        echo -e "\n"
                        echo -e "${txtgreen}SHOW ALL DATA OF ADDRESS BOOK${txtreset}"
                        echo -e "\n"
                        sqlite3 -header -column "$DATABASE" "SELECT * FROM address;"
                        sleep 5 
                        SEARCH_MENU_STATE="field"
                        REPLY=""
                        true	
                    ;;
                esac
            fi
        fi
    fi
	true;
}

function choose_search_menu_option()
{
    if [[ $SEARCH_EDIT_STATE == "search" ]]; then
        if [[ $SEARCH_MENU_STATE == "field" ]]; then
            local option="$REPLY"
            case $option in
                1)
                    SEARCH_MENU_STATE="Name"
                ;;

                2)
                    SEARCH_MENU_STATE="Email"
                ;;

                3)
                    SEARCH_MENU_STATE="Telephone Number"
                ;;

                4)
                    SEARCH_MENU_STATE="Mobile Number"
                ;;

                5)
                    SEARCH_MENU_STATE="Place"
                ;;

                6)
                    SEARCH_MENU_STATE="Message"
                ;;

                7)
                    SEARCH_MENU_STATE="All"
                ;;

                x)
                    SEARCH_MENU_STATE="field"
                    MENU_STATE="menu_header"
                ;;
            esac
        fi
    fi
}

#-----------------------------SEARCH MENU-------------------------------#
function show_search_result()
{
    if [[ $SEARCH_EDIT_STATE == "edit" ]]; then
        if [[ $flag_show_search == "true" ]]; then
            local result
            result=$(sqlite3 "$DATABASE" "SELECT * FROM address WHERE id='$id';")
            IFS=$'\n' read -d '' -r -a lines <<< "$result"
            IFS='|' read -r i0 i1 i2 i3 i4 i5 i6 <<< "$lines"
            name="$i1"
            email="$i2"
            tel_no="$i3" 
            mob_no="$i4"
            place="$i5"
            message="$i6"
            flag_show_search=false
        fi
    fi
}

function choose_edit_menu_option()
{
    if [[ $SEARCH_EDIT_STATE == "edit" ]]; then
        if [[ $EDIT_MENU_STATE == "field" ]]; then
            local option="$REPLY"
            case $option in
                1)
                    EDIT_MENU_STATE="Name"
                ;;

                2)
                    EDIT_MENU_STATE="Email"
                ;;

                3)
                    EDIT_MENU_STATE="Telephone Number"
                ;;

                4)
                    EDIT_MENU_STATE="Mobile Number"
                ;;

                5)
                    EDIT_MENU_STATE="Place"
                ;;

                6)
                    EDIT_MENU_STATE="Message"
                ;;

                7)
                    EDIT_MENU_STATE="Save"
                ;;

                x)
                    EDIT_MENU_STATE="field"
                    MENU_STATE="menu_header"
                ;;
            esac
        fi
    fi
}

function update_database()
{
    # echo "$id $name $email $tel_no $mob_no $place $message"
    local current_time
    current_time=$(date '+%Y-%m-%d %H:%M:%S')
    sqlite3 "$DATABASE" "UPDATE address SET name='$name', email='$email', tel_no='$tel_no', mob_no='$mob_no', place='$place', message='$message' WHERE id=$id;" 
    log "UPDATE" "$current_time"
    id=""
    # echo "Update database"
    # sleep 4
}

function edit_operation()
{
	# TODO Provide an option to change fields of an entry
	# 1. Ask user about the field to edit
	# 2. As per user selection, prompt a message to enter respected value
	# 3. Verify the user entry to field for matching. Eg mob number only 10 digits to enter
    # 4. Prompt error in case any mismatch of entered data and fields	
    if [[ $SEARCH_EDIT_STATE == "edit" ]]; then
        if [[ $EDIT_MENU_STATE != "field" ]]; then
            local option="$REPLY"
            case $EDIT_MENU_STATE in
                "Name")
                    validate_entry "$option" "$EDIT_MENU_STATE"
                    if [[ $flag_edit_entry_error == "false" ]]; then
                        EDIT_MENU_STATE="field"
                    fi
                    REPLY="" 
                ;;

                "Email")
                    validate_entry "$option" "$EDIT_MENU_STATE"
                    if [[ $flag_edit_entry_error == "false" ]]; then
                        EDIT_MENU_STATE="field"
                    fi
                    REPLY="" 
                ;;

                "Telephone Number")
                    validate_entry "$option" "$EDIT_MENU_STATE"
                    if [[ $flag_edit_entry_error == "false" ]]; then
                        EDIT_MENU_STATE="field"
                    fi
                    REPLY="" 
                ;;

                "Mobile Number")
                    validate_entry "$option" "$EDIT_MENU_STATE"
                    if [[ $flag_edit_entry_error == "false" ]]; then
                        EDIT_MENU_STATE="field"
                    fi
                    REPLY="" 
                ;;

                "Place")
                    validate_entry "$option" "$EDIT_MENU_STATE"
                    if [[ $flag_edit_entry_error == "false" ]]; then
                        EDIT_MENU_STATE="field"
                    fi
                    REPLY="" 
                ;;

                "Message")
                    message="$option"
                    EDIT_MENU_STATE="field"
                    REPLY=""
                ;;

                "Save")
                    update_database             
                    reset_global_value
                    echo -e "${txtgreen}SAVE VALUE TO ADDRESS DATABASE${txtreset}"
                    sleep 3
                    EDIT_MENU_STATE="field"
                    SEARCH_EDIT_STATE="search"
                    MENU_STATE="menu_header"
                    flag_show_search="true"
                ;;
            esac
        fi
    fi
	true;
}

#-----------------------------LOG FILE-------------------------------#
function log()
{
	# TODO Write activities to log files along with timestamp, pass argument as a string
    mode="$1"
    time="$2"
    case $mode in
        "INSERT")
	        sqlite3 "$DATABASE" "INSERT INTO log (id_address_book, name, email, tel_no, mob_no, place, message, mode, time) VALUES ( '$id_temp', '$name', '$email', '$tel_no', '$mob_no', '$place', '$message', '$mode', '$time');"		
        ;;

        "UPDATE")
	        sqlite3 "$DATABASE" "INSERT INTO log (id_address_book, name, email, tel_no, mob_no, place, message, mode, time) VALUES ( '$id', '$name', '$email', '$tel_no', '$mob_no', '$place', '$message', '$mode', '$time');"		
        ;;

        "DELETE")
            local result
            result=$(sqlite3 "$DATABASE" "SELECT * FROM address WHERE id='$id';")
            IFS=$'\n' read -d '' -r -a lines <<< "$result"
            IFS='|' read -r l0 l1 l2 l3 l4 l5 l6 <<< "$lines"
            name_log="$l1"
            emall_log="$l2"
            tel_no_log="$l3" 
            mob_no_log="$l4"
            place_log="$l5"
            message_log="$l6"
            flag_show_search_log=false
            sqlite3 "$DATABASE" "INSERT INTO log (id_address_book, name, email, tel_no, mob_no, place, message, mode, time) VALUES ( '$id', '$name_log', '$email_log', '$tel_no_log', '$mob_no_log', '$place_log', '$message_log', '$mode', '$time');"		
        ;;

    esac
	true;
}

function show_log_file()
{
    echo -e "\n"
    echo -e "${txtblue}SHOW LOG FILE${txtreset}"
    echo -e "\n"
    sqlite3 -header -csv "$DATABASE" "SELECT * FROM log;" > "$LOG_FILE_CSV"
    sqlite3 -header -csv "$DATABASE" "SELECT * FROM address;" > "$ADDRESS_DATABASE_CSV" 
    sqlite3 -header -column "$DATABASE" "SELECT * FROM log;" 
    echo -e "\n"
    echo -e "Find log file in directory ${txtyellow}log${txtreset}"
    read -r -p "Press Enter to escape"
    MENU_STATE="menu_header"
}

#-----------------------------SHOW UI-------------------------------#
function show_UI()
{
	case $MENU_STATE in
		"menu_header") 
			menu_header
			choose_header_option
		;;

		"field_menu")
			# The order below is important. Don't change
			field_menu
			add_entry
			choose_field_menu_option
		;;

		"search_edit_entry")
			# The order below is important. Don't change
			change_between_search_edit
			search_and_edit
			search_operation
			choose_search_menu_option	
            show_search_result
            edit_operation
            choose_edit_menu_option
		;;

        "log_file")
            show_log_file
        ;;
	esac
	true;
}

#-----------------------------MAIN SCRIPT-------------------------------#
while [[ true ]]; do
	show_UI
done
