#!/bin/bash

# The file names
#TODO Define all file names used for this project
# The file paths
#TODO Define all file paths here
# The globals
name=" "
email=" "
tel_no=" "
mob_no=" "
place=" "
message=" "

# Time out periods
TIME_OUT=10

# Menu state
MENU_STATE="menu_header"

# Set the path to the database 
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATABASE="$SCRIPT_DIR/mydatabase.db"

# Ensure the database file exists
if [ ! -f "$DATABASE" ]; then
	sqlite3 "$DATABASE" "CREATE TABLE IF NOT EXISTS address(
							id INTEGER PRIMARY KEY AUTOINCREMENT,
							name TEXT NOT NULL,
							email TEXT NOT NULL,
							tel_no TEXT,
							mob_no TEXT,
							place TEXT,
							message TEXT
	);"
fi

function log()
{
	# TODO Write activities to log files along with timestamp, pass argument as a string
	true;
}

function menu_header()
{
	# TODO Just to print welcome menu presntation
	clear
	cat <<- _EOF_
		My Database Project
		Please choose the below options:

		1. Add Entry
		2. Search / Edit Entry
		x. Exit

		Note: Script Timeout is set
	_EOF_
	read -p "Please choose your option: "

	true;
}

function choose_header_option()
{
	# TODO Just to choose the menu header option
	local option="$1"
	case "$REPLY" in
		1)
			MENU_STATE="add_entry"
			echo $MENU_STATE
			sleep 1
		;;

		2)
			MENU_STATE="search_edit_entry"
			echo $MENU_STATE
			sleep 1
		;;

		*)
			MENU_STATE="menu_header"
			echo $MENU_STATE
			sleep 1
			exit 0
	esac
}

function show_UI()
{

}

function field_menu()
{
	# TODO to print a selected user information 
	# Name, Email, Tel no, Mob num, Address, Message
	clear
	cat <<- _EOF_
		My Database Project
		Please choose the below options:

		Add New Entry Screen:

		1. Name			: $name
		2. Email		: $email
		3. Tel No		: $tel_no
		4. Mob No		: $mob_no
		5. Place		: $place
		6. Message		: $message
		x. Exit

	_EOF_
	read -p "Please choose the field to be added: "

	true;
}

function edit_operation()
{
	# TODO Provide an option to change fields of an entry
	# 1. Ask user about the field to edit
	# 2. As per user selection, prompt a message to enter respected value
	# 3. Verify the user entry to field for matching. Eg mob number only 10 digits to enter
    # 4. Prompt error in case any mismatch of entered data and fields	
	true;
}

function search_operation()
{
	# TODO Ask user for a value to search
	# 1. Value can be from any field of an entry.
	# 2. One by one iterate through each line of database file and search for the entry
	# 3. If available display all fiels for that entry
	# 4. Prompt error incase not available
	true;
}

function search_and_edit()
{
	# TODO UI for editing and searching 
	# 1. Show realtime changes while editing
	# 2. Call above functions respectively
	true;
}

function database_entry()
{
	# TODO user inputs will be written to database file
	# 1. If some fields are missing add consicutive ','. Eg: user,,,,,
	true;
}

function validate_entry()
{
	# TODO Inputs entered by user must be verified and validated as per fields
	# 1. Names should have only alphabets
	# 2. Emails must have a @ symbols and ending with .<domain> Eg: user@mail.com
	# 3. Mobile/Tel numbers must have 10 digits .
	# 4. Place must have only alphabets
	true;
}

function add_entry()
{
	# TODO adding a new entry to database
	# 1. Validates the entries
	# 2. Add to database
	true;
}

#ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Main script
while [[ 1 ]]; do
	#TODO
	menu_header;
	choose_header_option;
	# field_menu;
	# name="Test"
done
